---
title: "Calculatibg Coordinates"
author: "Edson Silva-Júnior"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Calculating coordinates based on Azhimute degrees and distances

$$
\varphi_{2} = \arcsin \left ( \sin(\varphi_{1}) * \cos \left (\frac{d}{R} \right) + \cos \left (\varphi_{1} \right) * \sin \left (\frac{d}{R} \right) * \cos \left (\theta \right) \right)
$$

$$
\lambda_{2} = \lambda_{1} + \arctan^2 \left(\sin \left(\theta \right) * \sin \left(\frac{d}{R} \right) * \cos \left (\varphi_{1} \right) * \cos \left (\frac{d}{R} \right) - \sin(\varphi_{1}) * \sin(\varphi_{2})\right)
$$

# Packages

```{r}
library(readxl)

library(tidyverse)

library(geosphere)

library(sf)
```

# Data 

## Importing

```{r}
coord <- readxl::read_xlsx("coordinates.xlsx")
```

## Visualizing

```{r}
coord

coord |> dplyr::glimpse()
```

# Calculating coordinates 

## Creating a coordinates calculating function

```{r}
coord_calcule <- function(id){
  
  if(coord$long[id] |> is.na() | coord$lat[id] |> is.na()){
    
    coordinate <- geosphere::destPoint(p = coord[id - 1, 1:2],
                                       b = coord[id - 1, 3],
                                       d = coord[id - 1, 4])
    
    coord$long[id] <<- coordinate[1]
    
    coord$lat[id] <<- coordinate[2]
    
  }
  
}
```


## Executing loop

```{r}
purrr::map(1:nrow(coord), coord_calcule)

coord
```

